name: citreas
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  money_converter: ^2.0.2
  cupertino_icons: ^1.0.2
  amplify_flutter: ^1.4.0
  amplify_auth_cognito: ^1.4.0
  amplify_api: ^1.4.0
  amplify_datastore: ^1.4.0
  amplify_authenticator: ^1.4.0
  amplify_core: ^1.4.0
  get: 4.6.5
  intl_phone_number_input: ^0.7.0+2
  web3dart: ^2.6.1
  flutter: 
    sdk: flutter
  http: ^0.13.0
  intl: ^0.18.0
  chart_sparkline: ^1.0.13
  syncfusion_flutter_charts: ^22.2.9

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NexaRegular.otf
        - asset: assets/fonts/NexaBold.otf
        # - asset: assets/fonts/Raleway-Regular.ttf
        # - asset: assets/fonts/Raleway-SemiBold.ttf
       


